language: c
compiler: clang
os: osx

addons:
  homebrew:
    update: true
    packages:
      - glib
      - gnutls
      - yajl

matrix:
  include:
    - osx_image: xcode11.3

script:
  - for i in `find /usr/local | grep .dylib` ; do echo $i ; otool -L $i ; echo ; echo ; done
  - MODS="glib-2.0 gobject-2.0 gio-2.0 gnutls libxml-2.0 libcurl libssh yajl"
  - CFLAGS=`pkg-config --cflags $MODS`
  - LIBS=`pkg-config --libs $MODS`
  - echo clang -o hello $CFLAGS $LIBS hello.c
  - clang -o hello $CFLAGS $LIBS hello.c
  - ./hello
  - otool -L hello
