language: c
compiler: clang
os: osx

addons:
  homebrew:
    update: true
    packages:
      - glib
      - gnutls

matrix:
  include:
    - osx_image: xcode11.3

script:
  - gcc -o hello `pkg-config --cflags --libs glib-2.0 gnutls` hello.c
  - ./hello
